version: '3'
services:
    nginx:
        image: nginx:alpine
        network_mode: bridge
        environment:
            - VIRTUAL_HOST=${PROJECT_URL}
        volumes:
            - ./src:/code
            - ./src/site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
    php:
        image: php:7.2-fpm-alpine3.10
        network_mode: bridge
        volumes:
            - ./src:/code